version: '3'
services:

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: server
    ports:
      - 8080:8080
    volumes:
      - "./server/:/usr/src/app/server"

    command: "npx nodemon -L server.js"

  next-js:
    build:
      context: ./shelter-system
      dockerfile: ./Dockerfile
    container_name: next-js
    depends_on:
      - server
    ports:
      - 3000:3000
    volumes:
      - "./shelter-system/:/usr/src/app/shelter-system"
